In [2]:
import numpy as np

In [3]:
arr1=np.array([1,2,3])

In [4]:
arr1

array([1, 2, 3])

In [5]:
arr2=np.array([[1,2,3],[4,5,6]])

In [6]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
list1=[1,2,3,4,5,6]

arr3=np.array(list1)

arr3

array([1, 2, 3, 4, 5, 6])

In [8]:
arr4=np.arange(1,100)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
arr5 =np.zeros((5,5))

In [10]:
arr9 =np.zeros(8)
arr9

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
arr3d=arr9.reshape(2,2,2)
arr3d

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [12]:
arr=arr3d.ravel()
arr

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
arr5


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
arr6= np.linspace(0,20,5)
arr6

array([ 0.,  5., 10., 15., 20.])

In [15]:
x=[1,2,3]

arr7=np.asarray(x)

arr7

array([1, 2, 3])

In [16]:
arr7[1]

2

In [17]:
arr11=np.arange(1,100)
arr11

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
arr_Slice=slice(1,10,2)
arr_Slice

slice(1, 10, 2)

In [19]:
element =arr11[6]
element

7

In [20]:
print(arr11[arr_Slice])

[ 2  4  6  8 10]


In [21]:
arr11[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [22]:
arr11[:15]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [23]:
arr12 =np.array([[1,2,3],[4,5,6],[7,8,9]])
arr12

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr12[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [25]:
type(arr11)

numpy.ndarray

In [26]:
arr11.dtype

dtype('int64')

In [27]:
arr12=np.array([1,2,3],dtype=np.float)

In [28]:
arr12

array([1., 2., 3.])

In [29]:
arr12=np.array([1,2,3],dtype=np.float32)

In [30]:
arr12

array([1., 2., 3.], dtype=float32)

In [31]:
arr12.dtype

dtype('float32')

In [32]:
lst=[1,2,3]*3

In [33]:
lst

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [34]:
arr12*3

array([3., 6., 9.], dtype=float32)

In [35]:
l1=[1,2,3]
l2=[4,5,6]
l1+l2

[1, 2, 3, 4, 5, 6]

In [36]:
ar1=np.array([1,2,3])
ar2=np.array([1,2,3])
print(ar1+ar2)

[2 4 6]


In [37]:
ar1=np.array([1,2,3,'h'])


In [38]:
ar1.dtype

dtype('<U21')

In [39]:
ar1.shape

(4,)

In [40]:
ar3=np.array([[1,2,3],[4,5,6]])

In [41]:
ar3.shape

(2, 3)

In [42]:
ar4=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [43]:
ar4.shape

(3, 3)

In [44]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [45]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [46]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
arr.dtype

dtype('float64')

In [49]:
arr4=np.ones((3,4), dtype=np.int8)

In [50]:
arr4.dtype


dtype('int8')

In [51]:
arr4

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [52]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [53]:
np.linspace(0,40,5)

array([ 0., 10., 20., 30., 40.])

In [54]:
ar5=np.zeros(6)

In [55]:
ar6=ar5.reshape(2,3)
ar6

array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
ar6.ndim

2

In [57]:
ar5=np.zeros(8)

In [58]:
ar6=ar5.reshape(2,2,2)
ar6

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [59]:
ar6.dtype

dtype('float64')

In [60]:
ar6.shape

(2, 2, 2)

In [61]:
ar6.ndim

3

In [62]:
ar6.ravel()

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [63]:
ar7=np.arange(1,21)
ar7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [64]:
ar7[1:5]

array([2, 3, 4, 5])

In [65]:
ar7[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [66]:
arr_Slice=slice(1,10,3)

In [67]:
ar7[arr_Slice]

array([2, 5, 8])

In [68]:
ar8=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [69]:
ar8.ndim

2

In [70]:
ar8.dtype

dtype('int64')

In [71]:
ar8

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [72]:
ar8[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [73]:
ar9=np.empty((3,5), dtype=int)

In [74]:
ar9

array([[2305843009213693952, 2305843009213693952,                   9,
                          0,                   0],
       [                  0,                   0,                   0,
                          0,                   0],
       [                  0,                   0,                   0,
                          0, 2305843009213693952]])

In [75]:
import numpy as np
path='/Users/atul595525/Desktop/sample.csv'
arr=np.loadtxt(path,delimiter =',',dtype=np.float32)
arr

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]], dtype=float32)

In [76]:
np.savetxt('output.txt',arr,fmt="%1.d")

In [77]:
print(np.savetxt.__doc__)


    Save an array to a text file.

    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:

        * a single specifier, `fmt='%.4e'`, resulting in numbers formatted
          like `' (%s+%sj)' % (fmt, fmt)`
        * a full string specifying every real and imaginary part, e.g.
          `' %.4e %+.4ej %.4e %+.4ej %.4e %+.4ej'` for 3 columns
        * a list of specifiers, one per column - in this case, the real
          and imaginary part must have separate specifiers,
     

In [78]:
import pandas as pd

series=pd.Series()

print(series)

Series([], dtype: float64)


In [79]:
arr123=np.array([1,2,3,4])

series=pd.Series(arr123)

print(series)


0    1
1    2
2    3
3    4
dtype: int64


In [80]:
dict={"a":20,"b":30,"c":40}

In [81]:
series1=pd.Series(dict)
series1

a    20
b    30
c    40
dtype: int64

In [82]:
series2=pd.Series([1,2,3,4,5,6,7,8,9])
print(series2[1:4])

1    2
2    3
3    4
dtype: int64


In [83]:
series2=pd.Series([1,2,3,4,5,6,[7,8,9]])

In [84]:
series2

0            1
1            2
2            3
3            4
4            5
5            6
6    [7, 8, 9]
dtype: object

In [85]:
list1=[1,2,3,4,5,6]

df=pd.DataFrame(list1)

df

0
0  1
1  2
2  3
3  4
4  5
5  6

In [86]:
dict1=[{"a":1,"b":2,"c":3},{"a":10,"b":20}]

df1=pd.DataFrame(dict1)

df1

a   b    c
0   1   2  3.0
1  10  20  NaN

In [87]:
dict2=[{"a":1,"b":2,"c":3},{"a":10,"b":20}]

df2=pd.DataFrame(dict2,index=['first','second'])

df2

a   b    c
first    1   2  3.0
second  10  20  NaN

In [88]:
data = {'one': pd.Series([10,20,30,40], index=["A","B","C","D"]),
        'two': pd.Series([10,20,30], index=["A","B","C"])
       }
df3=pd.DataFrame(data)
df3

one   two
A   10  10.0
B   20  20.0
C   30  30.0
D   40   NaN

In [89]:
df3['three']=pd.Series([1,2,3],index=["A","B","D"])

df3
                                      

one   two  three
A   10  10.0    1.0
B   20  20.0    2.0
C   30  30.0    NaN
D   40   NaN    3.0

In [90]:
del df3['one']

df3

two  three
A  10.0    1.0
B  20.0    2.0
C  30.0    NaN
D   NaN    3.0

In [91]:
df3.pop('two')


A    10.0
B    20.0
C    30.0
D     NaN
Name: two, dtype: float64

In [92]:
df3

three
A    1.0
B    2.0
C    NaN
D    3.0

In [93]:
df3

three
A    1.0
B    2.0
C    NaN
D    3.0

In [94]:
print(df3.loc['C'])

three   NaN
Name: C, dtype: float64


In [95]:
print(df3.iloc[2])

three   NaN
Name: C, dtype: float64


In [96]:
row=pd.DataFrame([[1,2],[3,4]],columns=['two','three'])

df3 =df3.append(row)

df3

/Users/atul595525/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)


three  two
A    1.0  NaN
B    2.0  NaN
C    NaN  NaN
D    3.0  NaN
0    2.0  1.0
1    4.0  3.0

In [97]:
df3 = df3.drop('A')
df3

three  two
B    2.0  NaN
C    NaN  NaN
D    3.0  NaN
0    2.0  1.0
1    4.0  3.0

In [98]:
df3 = df3.drop(0)
df3

three  two
B    2.0  NaN
C    NaN  NaN
D    3.0  NaN
1    4.0  3.0

In [99]:
df4 = pd.read_csv('/Users/atul595525/Desktop/learning/Edureka_courses/Python_For_Data_Science/Class_3_Deep_Dive_Functions_OOPs_Modules_Errors_andExceptions/574_m3_datasets_v3.0/bank-data.csv')
                  
df4.head(5)


age          job  marital    y
0   20      student   single  yes
1   32   management   single  yes
2   49   technician  married  yes
3   32  blue-collar  married  yes
4   33   management  married  yes

In [109]:
data = {'one': pd.Series([1,2,3,4], index=['a','b','c','d']), 'two': pd.Series([10,20,30,40], index=['a','b','c','d'])}





In [110]:

dfnew=pd.DataFrame(data)

dfnew

one  two
a    1   10
b    2   20
c    3   30
d    4   40

In [111]:
del dfnew['one']

dfnew

two
a   10
b   20
c   30
d   40

In [112]:
dfnew = dfnew.drop('a')
dfnew

two
b   20
c   30
d   40

In [113]:
df4 = pd.read_csv('/Users/atul595525/Desktop/learning/Edureka_courses/Python_For_Data_Science/Class_3_Deep_Dive_Functions_OOPs_Modules_Errors_andExceptions/574_m3_datasets_v3.0/bank-data.csv')
                  
df4.head(5)

age          job  marital    y
0   20      student   single  yes
1   32   management   single  yes
2   49   technician  married  yes
3   32  blue-collar  married  yes
4   33   management  married  yes

In [115]:
df4['age'].head(5)

0    20
1    32
2    49
3    32
4    33
Name: age, dtype: int64