In [ ]:
Case Study
Objective:
• Understand and practice linear discriminant analysis using scikit learn.

Questions:
    
1. We shall use the same dataset used in previous assignment - digits. Make a 80- 20 train/test split.
[Hint: Explore datasets module from scikit learn]

2. Using scikit learn perform a LDA on the dataset. Find out the number of components in the projected subspace.
[Hint: Refer to discriminant analysis module of scikit learn]

3. Transform the dataset and fit a logistic regression and observe the accuracy. Compare it 
with the previous model based on PCA in terms of accuracy and model complexity.
[Hint: Project both the train and test samples to the new subspace]
 

In [21]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
from sklearn import datasets
import matplotlib.pyplot as plt 


In [22]:
digits = load_digits()


# Create feature matrix
X = digits.data

# Create target vector
y = digits.target

# View the first observation's feature values
X[0]



array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [23]:
print(digits.data.shape)
print(digits.target.shape)
#print(digits.COL_NAMES)



(1797, 64)
(1797,)


In [24]:
y[0]

0

In [32]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(X,y, random_state = 10, test_size = 0.20)

In [33]:
'''
2. Using scikit learn perform a LDA on the dataset. Find out the number of components in the projected subspace.
[Hint: Refer to discriminant analysis module of scikit learn]

'''

'''
In the script above the LinearDiscriminantAnalysis class is imported as LDA. 
Like PCA, we have to pass the value for the n_components parameter of the LDA, 
which refers to the number of linear discriminates that we want to retrieve. 
In this case we set the n_components to 1, since we first want to check the performance of our classifier 
with a single linear discriminant. Finally we execute the fit and transform methods to actually retrieve 
the linear discriminants.

Notice, in case of LDA, the transform method takes two parameters: the X_train and the y_train. 
However in the case of PCA, the transform method only requires one parameter i.e. X_train. 
This reflects the fact that LDA takes the output class labels into account while selecting the linear discriminants, 
while PCA doesn't depend upon the output labels.


'''

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=5)
x_train = lda.fit_transform(x_train, y_train)
x_test = lda.transform(x_test)


/Users/atul595525/anaconda3/lib/python3.7/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [ ]:
'''
Training and Making Predictions
Since we want to compare the performance of LDA with one linear discriminant to the performance of PCA 
with one principal component, we will use the same Random Forest classifier that we used to evaluate performance of 
PCA-reduced algorithms.

Execute the following code:
'''

In [34]:
from sklearn.linear_model import LogisticRegression

ln_model = LogisticRegression()

ln_model.fit(x_train, y_train)

#classifier.fit(X_train, y_train)
y_pred = ln_model.predict(x_test)

In [35]:
#Evaluating the Performance

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' + str(accuracy_score(y_test, y_pred)))


[[36  0  0  0  1  0  0  0  0  0]
 [ 0 29  1  0  0  0  2  0  2  0]
 [ 0  0 34  0  0  0  0  0  0  0]
 [ 0  0  2 37  0  0  0  0  1  0]
 [ 1  2  0  0 29  0  1  0  0  1]
 [ 0  0  0  2  0 29  0  0  0  1]
 [ 0  1  0  0  0  0 36  0  0  0]
 [ 0  0  0  0  1  0  0 39  0  0]
 [ 0  9  1  0  0  0  0  0 22  1]
 [ 1  0  0  4  0  0  0  0  1 33]]
Accuracy0.9
