In [ ]:
1. Extract data from the given SalaryGender CSV file and store the data 
from each column in a separate NumPy array


In [26]:
import pandas as pd
import numpy as np

#data=pd.read_csv('/Users/atul595525/Desktop/learning/Edureka_courses/Python_For_Data_Science/Class_4_Introduction_to_NumPy_Pandas_and_Matplotlib/574_m4_datasets_v3.0/SalaryGender.csv')

#data.head(5)

np.load

data=np.genfromtxt('/Users/atul595525/Desktop/learning/Edureka_courses/Python_For_Data_Science/Class_4_Introduction_to_NumPy_Pandas_and_Matplotlib/574_m4_datasets_v3.0/SalaryGender.csv', delimiter=',', names=True)

data

salary= data['Salary']
gender=data['Gender']
age=data['Age']
phD=data['PhD']






AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [27]:
2. Find:
1. The number of men with a PhD
2. The number of women with a PhD





SyntaxError: invalid syntax (<ipython-input-27-479b43f227e2>, line 1)

In [43]:
# 1. The number of men with a PhD
df = pd.DataFrame(data)

df.head()


df_men_With_phd = df[(df['Gender']==1) & (df['PhD']==1)]

df_men_With_phd.count()


Salary    24
Gender    24
Age       24
PhD       24
dtype: int64

In [44]:
#2. The number of women with a PhD

df = pd.DataFrame(data)

df.head()



df_woman_With_phd = df[(df['Gender']==0) & (df['PhD']==1)]

df_woman_With_phd.head(5)

df_woman_With_phd.count()



Salary    15
Gender    15
Age       15
PhD       15
dtype: int64

In [45]:
df.count()

Salary    100
Gender    100
Age       100
PhD       100
dtype: int64

In [52]:
#3. Use SalaryGender CSV file. Store the “Age” and “PhD” columns in one DataFrame 
#and delete the data of all people who don’t have a PhD

df_new=df[['Age','PhD']]

df_new.head(5)

#df_new[df_new['PhD'] ==0]

df_new


# Get names of indexes for which column Age has value 30
indexNames = df_new[ df_new['PhD'] == 0 ].index

#indexNames
 
# Delete these row indexes from dataFrame
df_new.drop(indexNames , inplace=True)

df_new



/Users/atul595525/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3697: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


Age  PhD
0   47.0  1.0
1   65.0  1.0
4   53.0  1.0
8   44.0  1.0
9   63.0  1.0
12  60.0  1.0
17  47.0  1.0
18  66.0  1.0
19  45.0  1.0
25  66.0  1.0
26  36.0  1.0
28  51.0  1.0
29  65.0  1.0
30  45.0  1.0
31  52.0  1.0
32  54.0  1.0
38  34.0  1.0
41  58.0  1.0
42  77.0  1.0
45  48.0  1.0
47  49.0  1.0
49  65.0  1.0
54  49.0  1.0
56  61.0  1.0
57  43.0  1.0
60  66.0  1.0
63  56.0  1.0
73  71.0  1.0
76  69.0  1.0
77  58.0  1.0
79  32.0  1.0
80  33.0  1.0
81  32.0  1.0
87  42.0  1.0
89  51.0  1.0
90  71.0  1.0
92  55.0  1.0
94  55.0  1.0
96  56.0  1.0

In [ ]:
4. Calculate the total number of people who have a PhD degree from SalaryGender CSV file.

In [59]:
df_phd=df[df['PhD']==1]

df_phd.count()

Salary    39
Gender    39
Age       39
PhD       39
dtype: int64

In [ ]:
5. How do you Count The Number Of Times Each Value Appears In An Array Of Integers?
[0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9]

Answer should be array([4, 2, 1, 1, 3, 2, 0, 0, 0, 1]) which means 0 comes 4 times, 1 comes 2 times,
2 comes 1 time, 3 comes 1 time and so on.

In [67]:
data= [0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9]

import numpy as np

x=np.asarray(sorted(data,reverse=True))

x



array([9, 5, 5, 4, 4, 4, 3, 2, 1, 1, 0, 0, 0, 0])

In [ ]:
6. Create a numpy array [[0, 1, 2], [ 3, 4, 5], [ 6, 7, 8],[ 9, 10, 11]]) and filter the elements greater than 5.

In [75]:
import numpy as np

data_6=np.asarray([[0, 1, 2], [ 3, 4, 5], [ 6, 7, 8],[ 9, 10, 11]])
data_6.ndim

#2

data_6.shape

#(4, 3)

data_6

#reshaping array

data_6_rshp=data_6.ravel()

data_6_rshp


new_elem=[]
for elem in data_6_rshp:
    if elem>5:
        new_elem.append(elem)

new_elem

[6, 7, 8, 9, 10, 11]

In [ ]:
7. Create a numpy array having NaN (Not a Number) and print it. array([ nan, 1., 2., nan, 3., 4., 5.])
Print the same array omitting all elements which are nan


In [84]:
#an_array = np.empty((3,3))
#an_array[:] = np.NaN
#print(an_array)


import numpy
a = numpy.array([numpy.nan, 1,2,numpy.nan,3,4,5])
print(a)
print(a[~numpy.isnan(a)])


[nan  1.  2. nan  3.  4.  5.]
[1. 2. 3. 4. 5.]


In [ ]:
8. Create a 10x10 array with random values and find the minimum and maximum values.


In [89]:
ary=np.random.randint(101, size=(10, 10))

print(ary)
print(np.amax(ary))

print(np.amin(ary))


[[  6  54  55  22  86  64  94  81  53  73]
 [ 26  22  77  92  10  23  57   3  96  54]
 [ 62  51  94  65  49  96  10  13  85  43]
 [ 36  96  97  51  22  25  36   5  18  67]
 [100  83  25  36  32   2  91 100  62  80]
 [ 44  26  70  35  92  48  85   3  95  27]
 [  7  59  71  19  24  50  16   6  66  87]
 [ 94   5  95  52  70  52  55  50  84  46]
 [ 33  78  67   7  57   4  44   9  20  36]
 [ 98  99  22  28  61  88  43  61  49  96]]
100
2


In [ ]:
9. Create a random vector of size 30 and find the mean value.

In [91]:
import numpy as np
x = np.random.random(30)
print("Original array:")
print(x)


print(np.mean(x))




Original array:
[0.84481663 0.4927197  0.08840961 0.51911758 0.79105419 0.59089954
 0.34606271 0.01122453 0.62697161 0.02117047 0.91267398 0.71932302
 0.76226078 0.99754283 0.98355358 0.26252683 0.45745253 0.08554855
 0.76717561 0.47233347 0.09301565 0.84617644 0.32264639 0.14936489
 0.38201414 0.13562889 0.11886237 0.68813257 0.72829557 0.05408069]
0.4757018447044692


In [ ]:
10. Create numpy array having elements 0 to 10 And negate all the elements between 3 and 9


In [98]:
ary1=np.arange(11, dtype=int)

print(ary1)

c=np.where((ary1>2) & (ary1<10) ,ary1*-1,ary1)

print(c)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8 -9 10]


In [99]:
0

import numpy as np

arr = np.arange(11)

arr[3:9] = np.multiply(arr[3:9],-1)

print(arr)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [ ]:
11. Create a random array of 3 rows and 3 columns and sort it according to 1st column, 2nd column or 3rd column.


In [115]:
#Use the syntax array[:, j - 1] to extract the j-th column of an array. 
#Call numpy.argsort(a) to return the sorted indices of the column a. Then use these sorted 
#indices to sort the rows of the same array by column a.
#numpy.argsort()

#mat = np.array([[1,21,3],[5,4,2],[56,12,4]])
#mat_sort = mat[mat[:,2].argsort()]
#print(mat_sort)

#sorted_array = random_matrix_array[numpy.argsort(random_matrix_array[:, 0])]
import numpy as np
random_matrix_array = np.random.randint(1,10,size=(3,3))
print(random_matrix_array)
sorted_array = random_matrix_array[random_matrix_array[:,1].argsort()]
print(sorted_array)

[[8 9 1]
 [6 5 7]
 [1 3 1]]
[[1 3 1]
 [6 5 7]
 [8 9 1]]


In [108]:
12. Create a four dimensions array get sum over the last two axis at once. 

SyntaxError: invalid syntax (<ipython-input-108-4d4d083aac99>, line 1)

In [125]:
import numpy as np
#random_matrix_array2 = np.random.randint(1,10,size=(3))
#print(random_matrix_array)

array_4D = np.arange(64).reshape(4,2,4)

print(array_4D)

print(array_4D.ndim)

ValueError: cannot reshape array of size 64 into shape (4,2,4)

In [ ]:
13. Create a random array and swap two rows of an array.

In [127]:
a = np.array([[4,3,1], [5,7,0], [9,9,3], [8,2,4]])

a 
# array([[4, 3, 1],
#        [5, 7, 0],
#        [9, 9, 3],
#        [8, 2, 4]])



array([[4, 3, 1],
       [5, 7, 0],
       [9, 9, 3],
       [8, 2, 4]])

In [128]:
a[[0, 2]] = a[[2, 0]]
a
# array([[9, 9, 3],
#       [5, 7, 0],
#       [4, 3, 1],
#       [8, 2, 4]])

array([[9, 9, 3],
       [5, 7, 0],
       [4, 3, 1],
       [8, 2, 4]])

In [ ]:
14. Create a random matrix and Compute a matrix rank.

In [129]:
B = np.array([[4,3,1], [5,7,0], [9,9,3], [8,2,4]])

#A = numpy.matrix([[1,3,7],[2,8,3],[7,8,1]])

numpy.linalg.matrix_rank(B)



3